gos:
  finance:
    secrets: fs/src/main/resources/secrets.properties
    business-logic:
      symbol-exclusions:
        - "CS"

logging:
  file: finance-fs.log

spring:
  profile: general

name: general-profile
environment: general
